/** Abréviations provinces / régions corridor (Load Board, Truck Board). */
export const PROVINCE_ABBR: Record<string, string> = {
  'haut-katanga': 'HK',
  lualaba: 'LU',
  'haut-lomami': 'HL',
  tanganyika: 'TG',
  kinshasa: 'KN',
  'kongo-central': 'KC',
  kasai: 'KS',
  'kasai-central': 'KSC',
  'kasai-oriental': 'KSO',
  lomami: 'LO',
  sankuru: 'SK',
  maniema: 'MN',
  'sud-kivu': 'SKV',
  'nord-kivu': 'NKV',
  ituri: 'IT',
  tshopo: 'TS',
  'bas-uele': 'BU',
  'haut-uele': 'HU',
  mongala: 'MG',
  'nord-ubangi': 'NU',
  'sud-ubangi': 'SU',
  equateur: 'EQ',
  tshuapa: 'TH',
  kwango: 'KG',
  kwilu: 'KL',
  'mai-ndombe': 'MND',
  'zambie-central': 'ZC',
  'zambie-copperbelt': 'CB',
  'zambie-eastern': 'EA',
  'zambie-luapula': 'LP',
  'zambie-lusaka': 'LS',
  'zambie-muchinga': 'MU',
  'zambie-northern': 'NO',
  'zambie-north-western': 'NW',
  'zambie-southern': 'SO',
  'zambie-western': 'WE',
  'za-eastern-cape': 'EC',
  'za-free-state': 'FS',
  'za-gauteng': 'GT',
  'za-kwazulu-natal': 'KZN',
  'za-limpopo': 'LP',
  'za-mpumalanga': 'MP',
  'za-north-west': 'NW',
  'za-northern-cape': 'NC',
  'za-western-cape': 'WC',
  'tz-arusha': 'AR',
  'tz-dar-es-salaam': 'DSM',
  'tz-dodoma': 'DO',
  'tz-geita': 'GE',
  'tz-kagera': 'KA',
  'tz-kigoma': 'KI',
  'tz-kilimanjaro': 'KJ',
  'tz-mbeya': 'MB',
  'tz-morogoro': 'MO',
  'tz-mwanza': 'MW',
  'ao-benguela': 'BG',
  'ao-bie': 'BE',
  'ao-cabinda': 'CA',
  'ao-cunene': 'CN',
  'ao-huambo': 'HU',
  'ao-huila': 'HL',
  'ao-luanda': 'LU',
  'ao-lunda-norte': 'LN',
  'ao-lunda-sul': 'LS',
  'ao-moxico': 'MX',
};

export function getProvAbbr(prov: string) {
  return PROVINCE_ABBR[prov?.toLowerCase()] || prov?.substring(0, 3).toUpperCase() || '';
}
